name: PHP Composer

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: PHP Runner
      uses: franzliedke/gh-action-php@0.2.0
      
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
      
    - name: run php
      run: php ./json/generate15day.php
      
    - name: Commit files
      run: |
          git config --local user.email "test@biji.cf"
          git config --local user.name "zigou23"
          git add .
          git commit -m "update it at $(date +'%Y-%m-%d %H:%M:%S')"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.MY_GIT_TOKEN }}
        branch: main
          
