name: PHP Composer

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      
    - name: run php
      run: php ./json/generate15day.php
      
    - name: Commit files
      run: |
          git config --local user.email "test@biji.cf"
          git config --local user.name "zigou23"
          git add .
          git commit -m "update it at $(date +'%Y-%m-%d %H:%M:%S')"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
          
